[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

# SPA redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# CRITICAL: Fix MIME types for JavaScript modules - Must use text/javascript for modules
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*.mjs"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"

[[headers]]
  for = "*.mjs"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"

[[headers]]
  for = "*.jsx"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"

# Additional JS file patterns
[[headers]]
  for = "*.ts"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"

[[headers]]
  for = "*.tsx"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"

# CSS files
[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"

# Font files
[[headers]]
  for = "*.woff2"
  [headers.values]
    Content-Type = "font/woff2"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff"
  [headers.values]
    Content-Type = "font/woff"
    Cache-Control = "public, max-age=31536000, immutable"

# Model files
[[headers]]
  for = "/models/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "/tech-icons/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# HTML files
[[headers]]
  for = "*.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"

# JSON files
[[headers]]
  for = "*.json"
  [headers.values]
    Content-Type = "application/json; charset=utf-8"

# SVG files
[[headers]]
  for = "*.svg"
  [headers.values]
    Content-Type = "image/svg+xml; charset=utf-8"

# GLB/GLTF model files
[[headers]]
  for = "*.glb"
  [headers.values]
    Content-Type = "model/gltf-binary"
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "*.gltf"
  [headers.values]
    Content-Type = "model/gltf+json"
    Cache-Control = "public, max-age=2592000"

[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build"
